Time to finetune:
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
usage: train_text_to_image_lora.py [-h] --pretrained_model_name_or_path
                                   PRETRAINED_MODEL_NAME_OR_PATH
                                   [--revision REVISION]
                                   [--dataset_name DATASET_NAME]
                                   [--dataset_config_name DATASET_CONFIG_NAME]
                                   [--train_data_dir TRAIN_DATA_DIR]
                                   [--image_column IMAGE_COLUMN]
                                   [--caption_column CAPTION_COLUMN]
                                   [--validation_prompt VALIDATION_PROMPT]
                                   [--num_validation_images NUM_VALIDATION_IMAGES]
                                   [--validation_epochs VALIDATION_EPOCHS]
                                   [--max_train_samples MAX_TRAIN_SAMPLES]
                                   [--output_dir OUTPUT_DIR]
                                   [--cache_dir CACHE_DIR] [--seed SEED]
                                   [--resolution RESOLUTION] [--center_crop]
                                   [--random_flip]
                                   [--train_batch_size TRAIN_BATCH_SIZE]
                                   [--num_train_epochs NUM_TRAIN_EPOCHS]
                                   [--max_train_steps MAX_TRAIN_STEPS]
                                   [--gradient_accumulation_steps GRADIENT_ACCUMULATION_STEPS]
                                   [--gradient_checkpointing]
                                   [--learning_rate LEARNING_RATE]
                                   [--scale_lr] [--lr_scheduler LR_SCHEDULER]
                                   [--lr_warmup_steps LR_WARMUP_STEPS]
                                   [--snr_gamma SNR_GAMMA] [--use_8bit_adam]
                                   [--allow_tf32]
                                   [--dataloader_num_workers DATALOADER_NUM_WORKERS]
                                   [--adam_beta1 ADAM_BETA1]
                                   [--adam_beta2 ADAM_BETA2]
                                   [--adam_weight_decay ADAM_WEIGHT_DECAY]
                                   [--adam_epsilon ADAM_EPSILON]
                                   [--max_grad_norm MAX_GRAD_NORM]
                                   [--push_to_hub] [--hub_token HUB_TOKEN]
                                   [--prediction_type PREDICTION_TYPE]
                                   [--hub_model_id HUB_MODEL_ID]
                                   [--logging_dir LOGGING_DIR]
                                   [--mixed_precision {no,fp16,bf16}]
                                   [--report_to REPORT_TO]
                                   [--local_rank LOCAL_RANK]
                                   [--checkpointing_steps CHECKPOINTING_STEPS]
                                   [--checkpoints_total_limit CHECKPOINTS_TOTAL_LIMIT]
                                   [--resume_from_checkpoint RESUME_FROM_CHECKPOINT]
                                   [--enable_xformers_memory_efficient_attention]
                                   [--noise_offset NOISE_OFFSET] [--rank RANK]
train_text_to_image_lora.py: error: unrecognized arguments:  
Traceback (most recent call last):
  File "/home/bingxing2/home/scx6002/.conda/envs/test_sd_benchmark/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/bingxing2/home/scx6002/.conda/envs/test_sd_benchmark/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/bingxing2/home/scx6002/.conda/envs/test_sd_benchmark/lib/python3.8/site-packages/accelerate/commands/launch.py", line 979, in launch_command
    simple_launcher(args)
  File "/home/bingxing2/home/scx6002/.conda/envs/test_sd_benchmark/lib/python3.8/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/bingxing2/home/scx6002/.conda/envs/test_sd_benchmark/bin/python3.8', 'train_text_to_image_lora.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--dataset_name=lambdalabs/pokemon-blip-captions', '--resolution=512', '--center_crop', ' ']' returned non-zero exit status 2.
/var/spool/slurmd/job187654/slurm_script: line 21: --random_flip: command not found
Finished finetune
Cost time 10s
